// <auto-generated />
using System;
using Fuela.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace RentalPad.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20200823210919_v7")]
    partial class v7
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RentalPad.Models.Rental_Owners", b =>
                {
                    b.Property<int>("National_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Full_names")
                        .IsRequired()
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Phone_number")
                        .HasColumnType("int");

                    b.HasKey("National_id");

                    b.ToTable("Rental_owners");
                });

            modelBuilder.Entity("RentalPad.Models.Rentals_reg", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("National_id")
                        .HasColumnType("int");

                    b.Property<int>("No_rooms")
                        .HasColumnType("int");

                    b.Property<string>("R_location")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("R_name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int?>("Rental_OwnersNational_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("Rental_OwnersNational_id");

                    b.ToTable("Rentals_reg");
                });

            modelBuilder.Entity("RentalPad.Models.Room_Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Category")
                        .HasColumnType("int");

                    b.Property<string>("Rent_Ammount")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("Room_Category");
                });

            modelBuilder.Entity("RentalPad.Models.Rooms_reg", b =>
                {
                    b.Property<string>("Room_number")
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.Property<int>("Rental_reg")
                        .HasColumnType("int");

                    b.Property<string>("Room_category")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Room_number");

                    b.ToTable("Rooms_reg");
                });

            modelBuilder.Entity("RentalPad.Models.Tenants", b =>
                {
                    b.Property<int>("National_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("End_date")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Full_names")
                        .IsRequired()
                        .HasColumnType("varchar(50) CHARACTER SET utf8mb4")
                        .HasMaxLength(50);

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Phone_number")
                        .HasColumnType("int");

                    b.Property<int>("Rental_reg")
                        .HasColumnType("int");

                    b.Property<string>("Start_date")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("National_id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("RentalPad.Models.Rentals_reg", b =>
                {
                    b.HasOne("RentalPad.Models.Rental_Owners", "Rental_Owners")
                        .WithMany()
                        .HasForeignKey("Rental_OwnersNational_id");
                });
#pragma warning restore 612, 618
        }
    }
}
